-- Auto-generated by temp/export_tables_to_sql.js
-- Source table: drg_finding.adjrw_coefficients
-- Exported at: 2026-03-09T08:44:12.286Z

CREATE TABLE `adjrw_coefficients` (
  `coeff_set` varchar(4) COLLATE utf8mb4_unicode_ci NOT NULL,
  `drg_type` enum('M','P') COLLATE utf8mb4_unicode_ci NOT NULL,
  `rw_min` decimal(10,4) NOT NULL,
  `rw_max` decimal(10,4) NOT NULL,
  `b12` decimal(10,4) NOT NULL,
  `b23` decimal(10,4) NOT NULL,
  PRIMARY KEY (`coeff_set`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='สัมประสิทธิ์ b12/b23 สำหรับคำนวณ AdjRW ตามกลุ่ม DRG (แหล่ง: เล่ม1 Appendix H)';
INSERT INTO `drg_finding`.`adjrw_coefficients` (`coeff_set`, `drg_type`, `rw_min`, `rw_max`, `b12`, `b23`) VALUES
('M1', 'M', '0.0000', '0.6999', '0.0770', '0.0480'),
('M2', 'M', '0.7000', '100.0000', '0.1212', '0.0743'),
('P1', 'P', '0.0000', '1.9999', '0.0904', '0.0584'),
('P2', 'P', '2.0000', '100.0000', '0.1580', '0.1268');
