-- Auto-generated by temp/export_tables_to_sql.js
-- Source table: drg_finding.premdc_proc_groups
-- Exported at: 2026-03-09T08:44:12.250Z

CREATE TABLE `premdc_proc_groups` (
  `group_code` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `proc_code` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`group_code`,`proc_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO `drg_finding`.`premdc_proc_groups` (`group_code`, `proc_code`) VALUES
('boneMarrow', '4100'),
('boneMarrow', '4101'),
('boneMarrow', '4102'),
('boneMarrow', '4103'),
('boneMarrow', '4104'),
('boneMarrow', '4105'),
('boneMarrow', '4107'),
('boneMarrow', '4108'),
('boneMarrow', '4109'),
('heartLung', '3350'),
('heartLung', '3351'),
('heartLung', '3352'),
('heartLung', '336'),
('heartLung', '3751'),
('laryngectomy', '301'),
('laryngectomy', '303'),
('laryngectomy', '304'),
('liver', '5051'),
('liver', '5059');
